import type { ComponentResponse, ComponentType } from "@/shared/types/component"
import { COMPONENT_TYPE_LABEL } from "@/shared/types/component"
import type { SlotState } from "./compatibility"
import type { FpsResult } from "./fps"

/**
 * Generate a printable spec sheet HTML and trigger the browser's print dialog.
 * Using window.print() with an embedded iframe avoids @react-pdf/renderer's
 * 50KB+ bundle for what's basically a text document.
 */
export function exportBuildPdf(slots: SlotState, total: number, fps: FpsResult | null) {
  const components = Object.entries(slots)
    .filter((entry): entry is [ComponentType, ComponentResponse] => !!entry[1])
    .map(([type, c]) => ({ type: type as ComponentType, c }))

  const date = new Date().toLocaleDateString("th-TH", {
    year: "numeric",
    month: "long",
    day: "numeric",
  })

  const rows = components
    .map(
      ({ type, c }) => `
        <tr>
          <td>${COMPONENT_TYPE_LABEL[type]}</td>
          <td><strong>${escapeHtml(c.name)}</strong></td>
          <td style="text-align:right">฿${c.price.toLocaleString()}</td>
        </tr>`
    )
    .join("")

  const fpsBlock = fps
    ? `
      <h2>FPS Prediction @ 1080p</h2>
      <table>
        <tr><td>Valorant</td><td style="text-align:right"><strong>${fps.valorant} FPS</strong></td></tr>
        <tr><td>GTA V</td><td style="text-align:right"><strong>${fps.gta5} FPS</strong></td></tr>
        <tr><td>Cyberpunk 2077</td><td style="text-align:right"><strong>${fps.cyberpunk} FPS</strong></td></tr>
      </table>`
    : ""

  const html = `<!DOCTYPE html>
<html lang="th">
<head>
<meta charset="UTF-8">
<title>PC Build Spec</title>
<style>
  body { font-family: 'Prompt', sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; color: #000; }
  header { border-bottom: 2px solid #000; padding-bottom: 16px; margin-bottom: 24px; }
  .label { font-size: 10px; text-transform: uppercase; letter-spacing: 0.25em; color: #1d4ed8; font-weight: 700; }
  h1 { font-size: 32px; margin: 4px 0 0; font-weight: 800; letter-spacing: -0.02em; }
  h2 { font-size: 14px; text-transform: uppercase; letter-spacing: 0.25em; margin-top: 28px; margin-bottom: 12px; border-bottom: 1px solid #000; padding-bottom: 4px; }
  table { width: 100%; border-collapse: collapse; }
  td { padding: 8px 4px; border-bottom: 1px solid #e5e5e5; font-size: 14px; }
  tfoot td { border-top: 2px solid #000; border-bottom: none; padding-top: 12px; font-weight: 800; font-size: 16px; }
  footer { margin-top: 40px; font-size: 10px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.25em; }
</style>
</head>
<body>
  <header>
    <p class="label">PC Builder · Spec Sheet</p>
    <h1>ใบสเปกประกอบคอม</h1>
    <p style="margin-top:8px;color:#6b7280;font-size:12px">${date}</p>
  </header>

  <h2>ชิ้นส่วน</h2>
  <table>
    ${rows}
    <tfoot>
      <tr>
        <td colspan="2">รวม</td>
        <td style="text-align:right">฿${total.toLocaleString()}</td>
      </tr>
    </tfoot>
  </table>

  ${fpsBlock}

  <footer>
    Generated by PC Builder · pc-builder.app
  </footer>
</body>
</html>`

  // Embed in iframe and trigger print so the user can save as PDF
  const iframe = document.createElement("iframe")
  iframe.style.position = "fixed"
  iframe.style.left = "-10000px"
  iframe.style.top = "0"
  iframe.style.width = "1px"
  iframe.style.height = "1px"
  document.body.appendChild(iframe)

  const doc = iframe.contentDocument
  if (!doc) {
    document.body.removeChild(iframe)
    return
  }

  doc.open()
  doc.write(html)
  doc.close()

  iframe.onload = () => {
    iframe.contentWindow?.focus()
    iframe.contentWindow?.print()
    setTimeout(() => document.body.removeChild(iframe), 500)
  }
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
}
